const images: any = {
    logoBlack: require('~/assets/images/Logo5Star.png'),
    noImage: require('~/assets/images/no-image.png'),
    LoadingGif: require('./loading-gif.gif'),
    step1: require('~/assets/images/step1.png'),
    step2: require('~/assets/images/step2.png'),
    step3: require('~/assets/images/step3.png'),
    step4: require('~/assets/images/step4.png'),
    cards: require('~/assets/images/cards.png'),
    hero1: require('~/assets/images/hero1.png'),
    hero2: require('~/assets/images/hero2.png'),
    hero3: require('~/assets/images/hero3.png'),
    b_banner: require('~/assets/images/b_banner.jpg'),
    banner_sm01: require('~/assets/images/banner_sm01.png'),
    vector_login: require('~/assets/images/vector-login.png'),
    vector_register: require('~/assets/images/vector-signup.png'),
    spepay: require('~/assets/images/spepay.png'),
    momo: require('~/assets/images/momo.png'),
    avatarDefault: require('~/assets/images/avatar-default.png'),
    profile_account: require('~/assets/images/profile-myaccount.png'),
    bg_footer_l: require('~/assets/images/bg-footer-l.png'),
    bg_footer_r: require('~/assets/images/bg-footer-r.png'),
    special_1: require('~/assets/images/special-prod-1.jpg'),
    special_2: require('~/assets/images/special-prod-2.jpg'),
    special_4: require('~/assets/images/special-prod-4.jpg'),
    about_man: require('~/assets/images/about-man.png'),
    about_bg_dot: require('~/assets/images/about-bg-dot.png'),
    about_women: require('~/assets/images/about-women.jpg'),
    about_man_jean: require('~/assets/images/about-man-jean.jpg'),
};

export default images;
